name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: yarn
      - name: Install modules
        run: yarn install --immutable
      - name: Run ESLint & Prettier
        run: yarn run lint
      - name: Check types
        run: yarn run tsc

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: yarn
      - run: |
          git config user.name "O.A.F."
          git config user.email "<>"
      - run: yarn install --immutable
      - run: yarn run build
      - run: |
          mkdir -p publish/relay/high-speed-rail publish/data
          cp KoLmafia/data/high-speed-rail-load.js publish/data/
          cp KoLmafia/relay/choice.1485.js publish/relay/
          cp -R dist/* publish/relay/high-speed-rail/
      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: publish
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Release for commit ${{ github.sha }}: ${{ github.event.commits[0].message }}"
